const TOOL_CATEGORIES = {
  all: "全部",
  image: "AI 图片",
  text: "AI 文字",
  util: "实用工具",
};

const TOOL_LIST = [
  {
    id: "compress",
    name: "图片压缩",
    desc: "质量压缩，体积更小",
    category: "image",
    path: "/packageImage/compress/index",
    icon: "minimize",
  },
  {
    id: "copywriting",
    name: "AI 文案生成",
    desc: "小红书/朋友圈文案",
    category: "text",
    path: "/packageText/copywriting/index",
    icon: "pen-tool",
  },
  {
    id: "naming",
    name: "AI 起名字",
    desc: "多场景智能取名",
    category: "text",
    path: "/packageText/naming/index",
    icon: "sparkles",
  },
  {
    id: "nickname",
    name: "AI 网名生成",
    desc: "多风格个性网名",
    category: "text",
    path: "/packageText/nickname/index",
    icon: "at-sign",
  },
  {
    id: "word-count",
    name: "字数统计",
    desc: "实时统计字数与段落",
    category: "util",
    path: "/packageUtil/word-count/index",
    icon: "hash",
  },
  {
    id: "qrcode",
    name: "二维码生成",
    desc: "文字链接一键转码",
    category: "util",
    path: "/packageUtil/qrcode/index",
    icon: "smartphone",
  },
  {
    id: "collage",
    name: "图片拼图",
    desc: "2/4/6/9 宫格拼接",
    category: "image",
    path: "/packageImage/collage/index",
    icon: "image",
  },
  {
    id: "watermark",
    name: "图片加水印",
    desc: "平铺/单个文字水印",
    category: "image",
    path: "/packageImage/watermark/index",
    icon: "shield",
  },
  {
    id: "subsidy",
    name: "育儿补贴计算",
    desc: "估算可领取的育儿补贴",
    category: "util",
    path: "/packageUtil/subsidy/index",
    icon: "baby",
  },
  {
    id: "password",
    name: "随机密码",
    desc: "高强度密码一键生成",
    category: "util",
    path: "/packageUtil/password/index",
    icon: "lock",
  },
  {
    id: "xhs-cover",
    name: "AI 小红书封面",
    desc: "一键生成吸睛封面图",
    category: "image",
    path: "/packageImage/xhs-cover/index",
    icon: "image",
  },
  {
    id: "pet-avatar",
    name: "宠物Q版头像",
    desc: "AI 生成多风格萌宠头像",
    category: "image",
    path: "/packageImage/pet-avatar/index",
    icon: "pet",
  },
  {
    id: "tax-calculator",
    name: "个税计算器",
    desc: "2024新税率精准算税",
    category: "util",
    path: "/packageUtil/tax-calculator/index",
    icon: "calculator",
  },
  {
    id: "relative-calc",
    name: "亲戚称呼计算",
    desc: "过年不怕叫错人",
    category: "util",
    path: "/packageUtil/relative-calc/index",
    icon: "users",
  },
  {
    id: "life-simulator",
    name: "AI 人生模拟器",
    desc: "AI 书写你的随机人生",
    category: "text",
    path: "/packageText/life-simulator/index",
    icon: "gamepad",
  },
  {
    id: "dream-interpret",
    name: "AI 解梦",
    desc: "输入梦境，AI 为你解读",
    category: "text",
    path: "/packageText/dream-interpret/index",
    icon: "moon",
  },
  {
    id: "pregnancy-menu",
    name: "孕期菜谱",
    desc: "一键生成一周营养菜谱",
    category: "text",
    path: "/packageText/pregnancy-menu/index",
    icon: "utensils",
  },
  {
    id: "coming-soon",
    name: "更多工具",
    desc: "持续上新中",
    category: "all",
    path: "",
    icon: "more-horizontal",
  },
];

const ID_PHOTO_SIZES = [
  { key: "one", label: "1 寸", widthMm: 25, heightMm: 35 },
  { key: "two", label: "2 寸", widthMm: 35, heightMm: 49 },
  { key: "smallTwo", label: "小 2 寸", widthMm: 35, heightMm: 45 },
];

const BG_COLORS = [
  { key: "white", color: "#FFFFFF" },
  { key: "red", color: "#EF4444" },
  { key: "blue", color: "#3B82F6" },
  { key: "gray", color: "#D4D4D4" },
];

const AGENT_IDS = {
  copywriting: "ibot-zhiku-i8z7bi",
  naming: "ibot-zhiku-i8z7bi",
  nickname: "ibot-zhiku-i8z7bi",
  "dream-interpret": "ibot-zhiku-i8z7bi",
  "pregnancy-menu": "ibot-zhiku-i8z7bi",
};

module.exports = {
  TOOL_CATEGORIES,
  TOOL_LIST,
  ID_PHOTO_SIZES,
  BG_COLORS,
  AGENT_IDS,
};
